name: Release Drafter

on:
  push:
    branches:
      - main
    
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      -   name: Draft Release
          id: draft_release
          uses: release-drafter/release-drafter@v5
          with:
              disable-autolabeler: true
              commitish: main
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -   name: Checkout repo
          uses: actions/checkout@v3
          with:
              fetch-depth: 0
      -   name: Setup Node
          uses: actions/setup-node@v3
          with:
              node-version: 18
      -   name: NPM Install
          run: npm ci
      -   name: Run package update
          run: |
              TEMP_VERSION=${{ steps.draft_release.outputs.tag_name }}
              FINAL_VERSION="${TEMP_VERSION//v/}"
              npm run update:package -- -e "this.version='${FINAL_VERSION}'"
      -   name: Check if there is a change
          id: verify_diff
          run: |
              git diff --quiet package.json || echo "changed=true" >> $GITHUB_OUTPUT
      -   name: Commit and push changes
          if: steps.verify_diff.outputs.changed == 'true'
          uses: peter-evans/create-pull-request@v5
          with:
              token: ${{ secrets.GITHUB_TOKEN }}
              commit-message: Update system version
              committer: GitHub <noreply@github.com>
              author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
              branch: chore/update-version
              delete-branch: true
              title: 'Update package version'
              body: |
                  Update package version
              draft: false